APP_DEBUG: true

UseDbType: "mysql"                  #默认启用 mysql 数据库，备选项：mysql、sqlserver、

Mysql:
  Host: "127.0.0.1"
  DataBase: "db_stocks"
  Port: 3308                        #注意，非3306，请自行调整
  Prefix: "tb_"
  User: "root"
  Pass: "DRsXT5ZJ6Oi55LPQ"
  Charset: "utf8"
  SetMaxIdleConns: 10
  SetMaxOpenConns: 128
  SetConnMaxLifetime: 60
  PingFailRetryTimes: 3

SqlServer:
  Host: "127.0.0.1"
  DataBase: "db_goskeleton"
  Port: 1433
  Prefix: "tb_"
  User: "sa"
  Pass: "secret2017"
  SetMaxIdleConns: 10
  SetMaxOpenConns: 128
  SetConnMaxLifetime: 60
  PingFailRetryTimes: 3

Redis:
  Host: "127.0.0.1"
  Port: 6379
  Auth: ""
  MaxIdle: 10
  MaxActive: 1000
  IdleTimeout: 60
  IndexDb: 1

Websocket:                            #该服务与Http具有相同的ip、端口，因此不需要额外设置端口
  Start: 0                            #默认不启动该服务（1=启动；0=不启动）
  WriteReadBufferSize: 20480          # 读写缓冲区分配字节，大概能存储 6800 多一点的文字
  MaxMessageSize: 65535               # 从消息管道读取消息的最大字节
  PingPeriod: 30                      #心跳包频率，单位：秒
  HeartbeatFailMaxTimes: 4            # 允许心跳失败的最大次数（默认设置为PingPeriod=30秒检测一次，连续4次没有心跳就会清除后端在线信息）
  ReadDeadline: 0                     # 客户端在线情况下，正常的业务消息间隔秒数必须小于该值，否则服务器将会主动断开,单位：秒。 0 表示不设限制，即服务器不主动断开不发送任何消息的在线客户端

FileUploadSetting:
  Size: 32                            #设置上传文件的最大值，单位：M
  AllowMimeType:                      #允许的文件mime类型列表
    - "image/jpeg"                    #jpg、jpeg图片格式
    - "image/png"                     #png图片格式
    - "image/x-icon"                  #ico图片
    - "image/bmp"                     #bmp图片
    - "application/zip"               #xlsx、docx、zip
    - "application/x-gzip"            #tar.gz
    - "text/plain; charset=utf-8"     #txt log json等文本文件
