# 原生sql操作配置,从 v1.4.00 开始我们建议开发者统一使用 gorm v2操作数据库, 本人也开始参与开发此包，提交pr
# gorm v2 配置项参见同目录的 gorm_v2.yml 文件
RawSql:
  UseDbType: "mysql"                  #默认启用 mysql 数据库，备选项：mysql、sqlserver、postgre
  Mysql:
    Write:
      Host: "127.0.0.1"
      DataBase: "db_stocks"
      Port: 3308                        #注意，非3306，请自行调整
      Prefix: "tb_"
      User: "root"
      Pass: "DRsXT5ZJ6Oi55LPQ"
      Charset: "utf8"
      SetMaxIdleConns: 10               #空闲连接数
      SetMaxOpenConns: 128              #数据库连接池允许的最大连接数
      SetConnMaxLifetime: 60            # 连接不活动时的最大生存时间(秒)
      ReConnectInterval: 1              # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3
    IsOpenReadDb: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "192.168.8.62"
      DataBase: "db_stocks"
      Port: 3308                        #注意，非3306，请自行调整
      Prefix: "tb_"
      User: "root"
      Pass: "yourPassword"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      ReConnectInterval: 1    # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3

  SqlServer:
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      ReConnectInterval: 1     # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3    #从连接池获取连接失败，最大重试次数
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      ReConnectInterval: 1    # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3   #从连接池获取连接失败，最大重试次数

  PostgreSql:
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      ReConnectInterval: 1    # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
      ReConnectInterval: 1    # 数据库连接失败，每次重连时之间间隔秒数
      PingFailRetryTimes: 3